import type { BaseCommand, CommandCategoryId } from "./types";

export const commandCategories: { id: CommandCategoryId; label: string }[] = [
  { id: "A", label: "A 気道" },
  { id: "B", label: "B 呼吸" },
  { id: "C", label: "C 循環" },
  { id: "D", label: "D 中枢神経" },
  { id: "E", label: "E 環境" },
  { id: "X", label: "X 検査" }
];

export const commandCatalog: BaseCommand[] = [
  { id: "airwayCheck", category: "A", displayKind: "confirm", label: "気道開通の確認", duration: 1 },
  { id: "nasalAirway", category: "A", displayKind: "procedure", label: "経鼻エアウェイ", duration: 15 },
  { id: "oralAirway", category: "A", displayKind: "procedure", label: "経口エアウェイ", duration: 10 },
  { id: "intubation", category: "A", displayKind: "procedure", label: "気管挿管", duration: 35 },
  { id: "neckVeinCheck", category: "B", displayKind: "confirm", label: "頸静脈怒張の確認", duration: 1 },
  { id: "subcutaneousEmphysemaCheck", category: "B", displayKind: "confirm", label: "皮下気腫の確認", duration: 1 },
  { id: "trachealDeviationCheck", category: "B", displayKind: "confirm", label: "気管偏位の確認", duration: 1 },
  { id: "chestPalpation", category: "B", displayKind: "confirm", label: "前胸部触診", duration: 1 },
  { id: "spo2Monitor", category: "B", displayKind: "test", label: "SpO2モニターを装着", duration: 10 },
  { id: "oxygen", category: "B", displayKind: "procedure", label: "酸素投与", duration: 10 },
  { id: "niv", category: "B", displayKind: "procedure", label: "NIV装着", duration: 25 },
  { id: "ventilator", category: "B", displayKind: "procedure", label: "人工呼吸器装着", duration: 25 },
  { id: "thoracentesis", category: "B", displayKind: "procedure", label: "胸腔穿刺", duration: 15 },
  { id: "chestTube", category: "B", displayKind: "procedure", label: "胸腔ドレーン留置", duration: 35 },
  { id: "abdominalExam", category: "C", displayKind: "confirm", label: "腹部の視診・触診", duration: 3 },
  { id: "radialPulseCheck", category: "C", displayKind: "confirm", label: "橈骨動脈の触知確認", duration: 1 },
  { id: "bpCuff", category: "C", displayKind: "test", label: "血圧計を装着", duration: 5 },
  { id: "ecgMonitor", category: "C", displayKind: "test", label: "心電図を装着", duration: 5 },
  { id: "fast", category: "C", displayKind: "test", label: "FAST（超音波検査）", duration: 20 },
  { id: "iv", category: "C", displayKind: "procedure", label: "ルート確保", duration: 10 },
  { id: "centralLine", category: "C", displayKind: "procedure", label: "CV確保", duration: 45 },
  { id: "sheath", category: "C", displayKind: "procedure", label: "シース確保", duration: 30 },
  { id: "ecmo", category: "C", displayKind: "procedure", label: "ECMO留置", duration: 90 },
  { id: "pericardiocentesis", category: "C", displayKind: "procedure", label: "心嚢腔穿刺", duration: 25 },
  { id: "massiveFluid", category: "C", displayKind: "procedure", label: "大量輸液", duration: 25 },
  { id: "cardioversion", category: "C", displayKind: "procedure", label: "カルディオバージョン", duration: 10, repeatable: true },
  { id: "defibrillation", category: "C", displayKind: "procedure", label: "除細動", duration: 10, repeatable: true },
  { id: "transfusion", category: "C", displayKind: "procedure", label: "輸血", duration: 60, blocksCategory: false },
  { id: "ivr", category: "C", displayKind: "procedure", label: "IVR", duration: 45, blocksCategory: false },
  { id: "surgeryContact", category: "C", displayKind: "procedure", label: "外科医へ連絡", duration: 15 },
  { id: "adrenalineIvBolus", category: "C", displayKind: "medication", label: "アドレナリン1.0 mg 静注ボーラス投与", duration: 10 },
  { id: "adrenalineIm", category: "C", displayKind: "medication", label: "アドレナリン0.5 mg 筋注", duration: 10 },
  { id: "vasopressor", category: "C", displayKind: "medication", label: "ノルアドレナリン持続投与", duration: 20, repeatable: true },
  { id: "atropineIvBolus", category: "C", displayKind: "medication", label: "アトロピン1.0 mg 静注ボーラス投与", duration: 10 },
  { id: "consciousnessCheck", category: "D", displayKind: "confirm", label: "意識レベルの確認", duration: 1 },
  { id: "nerveBlock", category: "D", displayKind: "procedure", label: "神経ブロック", duration: 30 },
  { id: "sedation", category: "D", displayKind: "medication", label: "鎮静薬投与", duration: 10 },
  { id: "analgesia", category: "D", displayKind: "medication", label: "鎮痛薬投与", duration: 10 },
  { id: "temperatureMeasurement", category: "E", displayKind: "test", label: "体温測定", duration: 10 },
  { id: "warming", category: "E", displayKind: "procedure", label: "保温", duration: 10 },
  { id: "thermogardWarming", category: "E", displayKind: "procedure", label: "サーモガード留置: 加温", duration: 45 },
  { id: "thermogardCooling", category: "E", displayKind: "procedure", label: "サーモガード留置: 冷却", duration: 45 },
  { id: "plainCt", category: "X", displayKind: "test", label: "CT検査（単純）", duration: 45 },
  { id: "chestXray", category: "X", displayKind: "test", label: "胸部X線検査", duration: 20 }
];
